#!/usr/bin/env sh

#SKHD STUFF

# if you're having troubles finding key codes for a key just type skhd --observe in a terminal and type a key. Pretty cool! Or just check the wiki.

## HYPER == SHIFT + CMD + ALT + OPTION

## Quickly restart the yabai launch agent
hyper - y : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

## open terminal
hyper - return : Open -na /System/Applications/Utilities/Terminal.app

## send window to monitor and follow focus
#hyper - u : /Users/jesseskelton/CustomScripts/SwitchSpaces/moveWindowLeftAndFollowFocus.sh
#hyper - p : /Users/jesseskelton/CustomScripts/SwitchSpaces/moveWindowRightAndFollowFocus.sh

## focus display
ctrl + cmd - 1 : yabai -m window --display 1 yabai -m display --focus 1
ctrl + cmd - 2 : yabai -m window --display 2 yabai -m display --focus 2
ctrl + cmd - 3 : yabai -m window --display 3 yabai -m display --focus 3

## increase window size
#shift + alt - a : yabai -m window --resize left:-20:0
#shift + alt - s : yabai -m window --resize bottom:0:20
#shift + alt - w : yabai -m window --resize top:0:-20
#shift + alt - d : yabai -m window --resize right:20:0

## decrease window size
#shift + cmd - a : yabai -m window --resize left:20:0
#shift + cmd - s : yabai -m window --resize bottom:0:-20
#shift + cmd - w : yabai -m window --resize top:0:20
#shift + cmd - d : yabai -m window --resize right:-20:0

## rotate tree 90
hyper - r : yabai -m space --rotate 90

## flip the tree vertically
hyper - 4 : yabai -m space --mirror y-axis
# mirror tree y-axis
#alt - y : yabai -m space --mirror y-axis
## mirror tree x-axis
#alt - x : yabai -m space --mirror x-axis

## toggle window fullscreen zoom
hyper - f : yabai -m window --toggle zoom-fullscreen
